/*
 * This file is manually created (not generated by jOOQ).
 */
package com.ke.bella.openapi.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * AK模型白名单
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApikeyModelRelDB implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        akCode;
    private String        modelName;
    private Long          cuid;
    private String        cuName;
    private LocalDateTime ctime;

    public ApikeyModelRelDB() {}

    public ApikeyModelRelDB(ApikeyModelRelDB value) {
        this.id = value.id;
        this.akCode = value.akCode;
        this.modelName = value.modelName;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.ctime = value.ctime;
    }

    public ApikeyModelRelDB(
        Long          id,
        String        akCode,
        String        modelName,
        Long          cuid,
        String        cuName,
        LocalDateTime ctime
    ) {
        this.id = id;
        this.akCode = akCode;
        this.modelName = modelName;
        this.cuid = cuid;
        this.cuName = cuName;
        this.ctime = ctime;
    }

    /**
     * Getter for <code>apikey_model_rel.id</code>. 主键ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>apikey_model_rel.id</code>. 主键ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>apikey_model_rel.ak_code</code>. AK编码
     */
    public String getAkCode() {
        return this.akCode;
    }

    /**
     * Setter for <code>apikey_model_rel.ak_code</code>. AK编码
     */
    public void setAkCode(String akCode) {
        this.akCode = akCode;
    }

    /**
     * Getter for <code>apikey_model_rel.model_name</code>. 模型名称
     */
    public String getModelName() {
        return this.modelName;
    }

    /**
     * Setter for <code>apikey_model_rel.model_name</code>. 模型名称
     */
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    /**
     * Getter for <code>apikey_model_rel.cuid</code>. 创建人id
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>apikey_model_rel.cuid</code>. 创建人id
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>apikey_model_rel.cu_name</code>. 创建人姓名
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>apikey_model_rel.cu_name</code>. 创建人姓名
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>apikey_model_rel.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>apikey_model_rel.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ApikeyModelRelDB (");

        sb.append(id);
        sb.append(", ").append(akCode);
        sb.append(", ").append(modelName);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(ctime);

        sb.append(")");
        return sb.toString();
    }
}
